version: '3.9'

services:
  web:
    build: 
      context: .
      dockerfile:  docker/django/Dockerfile
    container_name: django_app
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - config/prod/.env
    environment:
      ENVIRONMENT: "${ENVIRONMENT}"
      DJANGO_SECRET_KEY: "${DJANGO_SECRET_KEY}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "${DB_HOST}"
    depends_on:
      - nginx

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
