# Generated by Django 5.1.3 on 2025-01-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('debit', 'Debit'), ('cash', 'Cash')], max_length=5),
        ),
    ]
