# Generated by Django 5.1.3 on 2024-12-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loan_total_interest_alter_loan_interest_rate_and_more'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='loans',
        ),
        migrations.AddField(
            model_name='person',
            name='loans',
            field=models.ManyToManyField(related_name='persons', to='loans.loan'),
        ),
    ]
