# Generated by Django 5.1.3 on 2024-12-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='total_interest',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loan',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='loan',
            name='payments',
        ),
        migrations.AddField(
            model_name='loan',
            name='payments',
            field=models.ManyToManyField(related_name='loans', to='payments.payment'),
        ),
    ]
