# Generated by Django 5.1.3 on 2025-01-08 00:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loan_payments_alter_loan_total_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=10),
        ),
    ]
