# Generated by Django 5.1.3 on 2025-01-20 23:52

from django.db import migrations, models


def find_person_for_loan(apps, loan):
    Person = apps.get_model('persons', 'Person')
    person = Person.objects.filter(loans=loan.pk)
    if person.exists():
        return person.first()
    return None


def set_person_field(apps, schema_editor):
    Loan = apps.get_model('loans', 'Loan')
    for loan in Loan.objects.all():
        person = find_person_for_loan(apps, loan)
        if person:
            loan.person = person
            loan.save()


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loan_original_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='person',
            field=models.ForeignKey(
                to='persons.Person',
                null=True,
                blank=True,
                on_delete=models.CASCADE,
                related_name='loans',
            ),
        ),
        migrations.RunPython(set_person_field),
        migrations.AlterField(
            model_name='loan',
            name='person',
            field=models.ForeignKey(
                to='persons.Person',
                on_delete=models.CASCADE,
                related_name='loans',
            ),
        ),
    ]
