# Generated by Django 5.1.3 on 2025-01-21 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_remove_loan_payments_loan_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='payments',
        ),
    ]
